package com.ficmart.gateway.payment;

public enum PaymentEventType {
    AUTHORIZATION_REQUESTED,
    AUTHORIZATION_SUCCEEDED,
    AUTHORIZATION_FAILED,
    CAPTURE_REQUESTED,
    CAPTURE_SUCCEEDED,
    CAPTURE_FAILED,
    VOID_REQUESTED,
    VOID_SUCCEEDED,
    VOID_FAILED,
    REFUND_REQUESTED,
    REFUND_SUCCEEDED,
    REFUND_FAILED,
    AUTHORIZATION_EXPIRED
}